---
title: "STAT 411/511 - Assignment 1"
author: "Your name"
date: "Date"
output: pdf_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#####GOAL  
The goal of this assignment is to review some fundamental statistical concepts and to provide more introduction to R statistical software.  You should complete the R Introduction before starting this assignment.  The format of this assignment is not indicative of future assignments in the course.  


#####ADVICE  
*Start early* and ask for help when and if you need it.  An R-code script is provided with the assignment.  R is challenging at first for most students, but developing some computer skills is important for your future.  I am more than happy to provide extra R help to those needing it.  Also, if you are just completely lost with this assignment come see me ASAP and think about whether STAT 401 might be a good option.  


#####FORMAT
To complete the assignment, edit this Rmd file through RStudio.  Show relevant R code in chunks where needed.  All work should be turned following the order in the assignment - this includes plots and they should be scaled appropriately. It is your job to convince me (1) you did the exercise and (2) that you understand the point of it (why did I ask you to do it?).  Include the plots you are asked to make unless it is explicitly stated otherwise.

***

####  Problem 1
Use the R code provided to simulate draws from a normally distributed population  (with `mean=0` and `sd=1`), and use histograms to investigate the observed data sets.  Repeat draws using samples sizes of `n=5`, `n=10`, `n=30`, and `n=200`

a. Discuss differences among the sample sizes in how close the histograms are to the standard normal curve.

b. Describe how the variability among the different draws (each of the same sample size) changes as sample size increases.  For example, when you compare histograms at n=5, are they more or less similar than the set of histograms constructed for n=30?

c. In this problem, we started with a population that is normally distributed, from which we then repeatedly drew different sets of data. In this course, we will frequently be given a single, observed set of data; and then we will be asked whether it could have come from a normally distributed population. How might this exercise help inform those descriptions?  

***

#### Problem 2
Generate a sample of 200 observations from a standard normal distribution (`mean=0` and `sd=1`) and plot them in a histogram. Calculate the proportion of those 200 values that are greater than or equal to 1.96 (use 4 decimal places).  Repeat using a sample size of 10,000; and, finally, use a built-in function for the normal distribution `pnorm()` to get an answer obtained by integrating the area under the normal density curve to the right of 1.96. Compare your answers and discuss why there is a difference. Is the difference is more or less than you expected?  You can conduct multiple draws and incorporate that into your discussion.   

***

#### Problem 3
Use the code and random draws from Problem 2 to find the following values.  Produce a plot with the relavent area under the normal curve shaded for each.

a. The proportion of values between -1 and 1

b. The proportion EXACTLY EQUAL to 0.5000000. This one is a bit tricky, but demonstrates an important property of continuous distributions.

c. Find a value such that 40\% of the draws are less than or equal to it (to the left).  You do not need to turn in the plot for this one.

d. Use the `qnorm()` function to find the analogous value directly from the normal curve, and draw a picture clearly labeling the 0.40 and the answer obtained.  Discuss how these two parts are related (make sure to use the word "approximation in your explanation).

e. Much of the basis for statistical inference comes from comparing an observed value (a test statistic) to its reference distribution  (aka a null distribution). The reference distribution may be derived either empirically, in the case of permutation tests, or theoretically for t-tests, etc. Suppose our observed test statistic have a value of 1.34.  Using `y.lots` as an empirical reference distribution, find the proportion of values MORE EXTREME than our observed test statistic.

f. In your first statistics course, you were likely asked to find values such as "What is the probability of standard normal random variable being less than 1.645?" or "What value from a standard normal distribution corresponds to having 95\% of values less than or equal to it?" or "What value from a standard normal distribution corresponds to having 5\% of values greater than it?" How does this exercise relate to those questions?   

***

#### Problem 4
Use the provided R code to work through the following steps.  For each graph, write a brief description of what the plot is showing.

a. First, let's generate some data 
    + Draw a set of 60 random observations from a normal distribution with a mean of 0 and a standard deviation of 2. 
    + Create a `data.frame` with these values, and add a column that gives each value a unique id.
    + Randomly assign half of the observations to treatment A and half to treatment B WITHOUT changing the order of the data.frame.
    + Let's pretend treatment B adds 3 to the original observation. Create a new column with a response variable that reflects this change.

b. Make a stem-and-leaf plot of the original observations.

c. Make side-by-side boxplots of the two treatments.  What does each part of the boxplot represent?

d. Make histograms for each treatment.

e. Put a histogram and a box plot together on the same plot for the initial observations.

f. Add a new set of observations to the dataset. Make a scatter plot with the first set of data on the x-axis and the second set on the y-axis.  
 
***

#### Problem 5  
Write a **Scope of Inference** for the following scenario, follow  examples from class.  Separately, identify a confounding variable that exists because of the study design.
    
>Education researchers were interested in comparing assessment between two different college-level introductory statistics courses (different context and teaching strategies).  There were four sections of 30 students available and two sections were taught of each curriculum.  There were two instructors for the course, one specializing in each curriculum.  Therefore, the two sections of each curriculum were taught by the same instructor.   At the end of the semester, the same assessment was given to all students.  Researchers were interested in whether there is evidence of a difference in mean final exam scores between the two types of courses. 
    
   